function main() {}

try {
  main();
} catch (e) {
  console.error(e);
  process.exit(1);
}
